import { test, expect } from "@playwright/test";
test("welcome, shortcuts, featured projects and tour are connected", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Open Welcome", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Welcome to Elisha Creatives", exact: true })).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Desktop shortcuts" }).getByRole("button")).toHaveCount(4);
  await expect(page.getByRole("button", { name: /Pricing/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Explore my work" }).click();
  const work = page.getByRole("dialog", { name: "Works", exact: true });
  await expect(work.getByRole("button", { name: "Featured", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(work.locator(".index-items button")).toHaveCount(3);
  await work.getByRole("button", { name: /A&B Accessories Poster/ }).click();
  await expect(work.getByRole("heading", { name: "Across the project" })).toBeVisible();
  await page.getByRole("button", { name: "Open Help", exact: true }).click();
  const help = page.getByRole("dialog", { name: "Workspace guide" });
  for (let i = 0; i < 5; i++) await help.getByRole("button", { name: "Next" }).click();
  await help.getByRole("button", { name: "Explore the work" }).click();
  await expect(help).toBeHidden();
  await expect(work).toBeVisible();
});
test("preferences persist, reduced motion stops video, music can be muted and resumed", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/#preferences");
  await expect(page.locator(".signature-motion img")).toBeVisible();
  await expect(page.locator(".signature-motion video")).toHaveCount(0);
  const prefs = page.getByRole("dialog", { name: "Preferences", exact: true });
  await prefs.getByRole("button", { name: "Plain dark" }).click();
  await prefs.getByRole("checkbox", { name: "Background motion" }).uncheck();
  await prefs.getByRole("checkbox", { name: "Interface sounds" }).check();
  await page.reload();
  await expect(prefs.getByRole("button", { name: "Plain dark" })).toHaveAttribute("aria-pressed", "true");
  await expect(prefs.getByRole("checkbox", { name: "Background motion" })).not.toBeChecked();
  await expect(prefs.getByRole("checkbox", { name: "Interface sounds" })).toBeChecked();
  await prefs.getByRole("button", { name: "Mute music", exact: true }).click();
  await prefs.getByRole("button", { name: "Unmute music", exact: true }).click();
  await expect.poll(() => page.locator("audio").evaluate((element: HTMLAudioElement) => !element.paused && element.currentTime > 0)).toBe(true);
  await prefs.getByRole("button", { name: "Mute music", exact: true }).click();
  expect(await page.locator("audio").evaluate((element: HTMLAudioElement) => element.paused)).toBe(true);
  await expect(prefs.getByRole("link", { name: "Creative Commons Attribution 4.0" })).toBeVisible();
});
test("About sections and the complete brand animation are available on mobile", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto("/#about");
  const about = page.getByRole("dialog", { name: "About Elisha", exact: true });
  await about.getByRole("button", { name: "Journey", exact: true }).click();
  await expect(about.getByText(/My freelance work began in 2024/)).toBeVisible();
  await about.getByRole("button", { name: "The brand", exact: true }).click();
  await expect(about.locator("video")).toHaveAttribute("controls", "");
  await about.getByRole("button", { name: "Home", exact: true }).click();
  await expect(page.getByRole("button", { name: "Preferences", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Mute music", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375);
});
